name: Generate RSS from Google Sheet

on:
  schedule:
    - cron: '24 * * * *'  # каждый час
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install gspread oauth2client

    - name: Decode creds.json
      run: |
        echo "${{ secrets.GDRIVE_CREDENTIALS }}" | base64 -d > creds.json    

    - name: Run script
      run: python3 gen_rss.py

    - name: Show push URL (debug)
      run: echo "https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git"
      
    - name: Commit and push
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add feed.xml
        git diff --cached --quiet || git commit -m "Update feed"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:main

